name: "Elemental agent"
stages:
  network.after:
    - if: '[ ! -f /run/elemental/live_mode ] && [ ! -f /run/elemental/recovery_mode ]'
      commands:
        - systemctl start elemental-agent.service
